---
cloudflare_zone_id: a80829b534d06a3ab95f513501ab997d
cytrus_host: 135.181.95.85
apps:
  - name: radzymin-petycje
    domain: "{{ domain | default('radzymin.mleczki.pl') }}"
    port: 8084
    image: "ghcr.io/mleczakm/radzymin.mleczki.pl:{{ app_version | default('latest') }}"
    env:
      APP_ENV: prod
      APP_VERSION: "{{ app_version | default('latest') }}"
      DB_PATH: /app/db/data.sqlite
      BASE_URL: "https://{{ domain | default('radzymin.mleczki.pl') }}"
      MAIL_FROM: kontakt@radzymin.mleczki.pl
      ORGANIZER_NAME: Michał Mleczko
      ORGANIZER_ADDRESS: zamieszkały w Radzyminie
      ORGANIZER_EMAIL: kontakt@radzymin.mleczki.pl
      CONTACT_FORM_ENDPOINT: https://formspree.io/f/xwlppzoj
    healthcheck_enabled: true
    ipv6: "{{ mikrus_ipv6 }}"
    cytrus_host: "{{ cytrus_host }}"
    proxied: true
    email_routing:
      address: kontakt@radzymin.mleczki.pl
      forward_to: do@mleczki.pl
